In [35]:
import numpy as np 


In [45]:
alphaValues = [0.001,0.01,0.1,5,10]
hiddenSize = 32
#Defining a sigmoid function 
def sigmoid(x):
    output = 1 / (1 + np.exp(-x))
    return output

    
#derivative of sigmoid function 
# Defining a sigmoid function


# derivative of sigmoid function
def sigmoidDerivativeFunction(output):
    output = output * (1 - output)
    return output

In [46]:
#Some values to construct the nural net work 
#Later we will be using the actual data from the iris data set 
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])


In [48]:
for alpha in alphaValues:
    print("\the current alpha value = ",alpha)
    np.random.seed(1)
    
    #initializing Random weights 
    
    weight_1 = 2*np.random.random((3,hiddenSize)) - 1
    weight_2 = 2*np.random.random((hiddenSize,1)) - 1
    
    #checking the weights to see how the gradiants are changing 
    
    weight_1_dirCount = np.zeros_like(weight_1)
    weight_2_dirCount = np.zeros_like(weight_2)
    
    
    
        
    prev_weight_1_update = np.zeros_like(weight_1)
    prev_weight_2_update = np.zeros_like(weight_2)
   

   
    for j in range(60000):
        #Forward propogation from one layer to another i.e between layers 0 , 1, 2
        #layer_0 = X
        #layer_1 = sigmoid(np.dot(layer_0,weight_1))   #Here we are multiplying   ThetaTranspose* X
        #print(type(layer_1))
        #layer_2 = sigmoid(np.dot(layer_1,weight_2)) # the same thing with respoect to the second layer .. ie thetaTranspose*X
        
        
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0,weight_1))
        layer_2 = sigmoid(np.dot(layer_1,weight_2))
        #Caliculating the error value 
        
        ForwardPropError = y - layer_2
        
        if (j%10000) == 0:
            print("Error = ",np.mean(np.abs(ForwardPropError)))
                  
        
        ##Back propogation 
        layer2_Sigma = ForwardPropError*sigmoidDerivativeFunction(layer_2)
        
        layer1_Error =  layer2_Sigma.dot(weight_2.T)
    
        layer_1Sigma = layer1_Error*sigmoidDerivativeFunction(layer_1)
        
        
                  
                  
    
        #We are suggesting values .. i.e how much of it is wrong in each layer 
        #baically updating the weights withs respective to values and the errors observed 
        weight_2_Update = (layer_1.T.dot(layer2_Sigma))
        weight_1_Update = (layer_0.T.dot(layer_1Sigma))
        
        #We are checking what direction the gradient is moving           
        if(j > 0):
                  weight_1_dirCount += np.abs(((weight_1_Update> 0)+0)-
                                             
                                             ((prev_weight_1_update>0)+0))
                  weight_2_dirCount += np.abs(((weight_2_Update> 0)+0)-
                                             
                                             ((prev_weight_2_update>0)+0))
        weight_1 += alpha*weight_1_Update
        weight_2 += alpha*weight_2_Update
                  
                  
                  
        prev_weight_1_update = weight_1_Update
        prev_weight_2_update = weight_2_Update
 
                  
    print("weight_1",weight_1)
    print("weight_2",weight_2)
                  
                  
                  
                  
        
        
        
    
    

	he current alpha value =  0.001
Error =  0.49643992250078794
Error =  0.49104946812904954
Error =  0.4849763070274596
Error =  0.4778306787926556
Error =  0.4690384653902826
Error =  0.458029258565275
weight_1 [[-0.66945036  0.44057532 -0.91759208 -0.36525547 -0.76011568 -0.82926418
  -0.61094522 -0.22947974 -0.67917735  0.15292538 -0.35220283  0.3339454
  -0.59142231  0.67756675 -1.11442476  0.54733702 -0.31555027  0.11348483
  -1.42577089 -0.75857317  0.67526556  0.75670996 -0.38885609  0.94740732
   0.79895388  1.35107823 -0.82206512 -0.99660592 -0.40374837  0.75100038
  -0.85239719 -0.11992929]
 [ 0.9583388   0.07763217  0.83646247 -0.34174625  0.57380012  0.64850887
  -0.90837847  0.49541604  0.96767225  0.50496084 -0.51623496  0.55803271
  -0.78484996 -0.25896594  1.37458204 -0.45776431 -0.51938006 -0.78121801
  -1.54926221  0.42897347 -0.82710662 -0.14644147  0.00949155 -1.04761586
  -0.17898997 -0.88967639 -0.25319071  0.77334008 -0.59686327 -0.16546404
   0.40869142 -0.146501

In [25]:
import numpy as np

alphas = [0.001,0.01,0.1,1,10,100,1000]

# compute sigmoid nonlinearity
def sigmoid(x):
    output = 1/(1+np.exp(-x))
    return output

# convert output of sigmoid function to its derivative
def sigmoid_output_to_derivative(output):
    return output*(1-output)
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])



for alpha in alphas:
    print("\nTraining With Alpha:" + str(alpha))
    np.random.seed(1)

    # randomly initialize our weights with mean 0
    synapse_0 = 2*np.random.random((3,4)) - 1
    synapse_1 = 2*np.random.random((4,1)) - 1
        
    prev_synapse_0_weight_update = np.zeros_like(synapse_0)
    prev_synapse_1_weight_update = np.zeros_like(synapse_1)

    synapse_0_direction_count = np.zeros_like(synapse_0)
    synapse_1_direction_count = np.zeros_like(synapse_1)
        
    for j in range(60000):

        # Feed forward through layers 0, 1, and 2
        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0,synapse_0))
        layer_2 = sigmoid(np.dot(layer_1,synapse_1))

        # how much did we miss the target value?
        layer_2_error = y - layer_2

        if (j% 10000) == 0:
            print("Error:" + str(np.mean(np.abs(layer_2_error))))

        # in what direction is the target value?
        # were we really sure? if so, don't change too much.
        layer_2_delta = layer_2_error*sigmoid_output_to_derivative(layer_2)

        # how much did each l1 value contribute to the l2 error (according to the weights)?
        layer_1_error = layer_2_delta.dot(synapse_1.T)

        # in what direction is the target l1?
        # were we really sure? if so, don't change too much.
        layer_1_delta = layer_1_error * sigmoid_output_to_derivative(layer_1)
        
        synapse_1_weight_update = (layer_1.T.dot(layer_2_delta))
        synapse_0_weight_update = (layer_0.T.dot(layer_1_delta))
        
        if(j > 0):
            synapse_0_direction_count += np.abs(((synapse_0_weight_update > 0)+0) - ((prev_synapse_0_weight_update > 0) + 0))
            synapse_1_direction_count += np.abs(((synapse_1_weight_update > 0)+0) - ((prev_synapse_1_weight_update > 0) + 0))        
        
        synapse_1 += alpha * synapse_1_weight_update
        synapse_0 += alpha * synapse_0_weight_update
        
        prev_synapse_0_weight_update = synapse_0_weight_update
        prev_synapse_1_weight_update = synapse_1_weight_update
    
    print("Synapse 0")
    print(synapse_0)
    
    print("Synapse 0 Update Direction Changes")
    print(synapse_0_direction_count)
    
    print("Synapse 1")
    print(synapse_1)

    print("Synapse 1 Update Direction Changes")
    print(synapse_1_direction_count)


Training With Alpha:0.001
Error:0.49641003190272537
Error:0.49516402549338606
Error:0.4935960431880486
Error:0.4916063585594306
Error:0.48910016654420474
Error:0.48597785784615843
Synapse 0
[[-0.28448441  0.32471214 -1.53496167 -0.47594822]
 [-0.7550616  -1.04593014 -1.45446052 -0.32606771]
 [-0.2594825  -0.13487028 -0.29722666  0.40028038]]
Synapse 0 Update Direction Changes
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 1.]]
Synapse 1
[[-0.61957526]
 [ 0.76414675]
 [-1.49797046]
 [ 0.40734574]]
Synapse 1 Update Direction Changes
[[1.]
 [1.]
 [0.]
 [1.]]

Training With Alpha:0.01
Error:0.49641003190272537
Error:0.45743107444190134
Error:0.359097202563399
Error:0.23935813715897253
Error:0.1430706590133703
Error:0.09859642980892719
Synapse 0
[[ 2.39225985  2.56885428 -5.38289334 -3.29231397]
 [-0.35379718 -4.6509363  -5.67005693 -1.74287864]
 [-0.15431323 -1.17147894  1.97979367  3.44633281]]
Synapse 0 Update Direction Changes
[[1. 1. 0. 0.]
 [2. 0. 0. 2.]
 [4. 2. 1. 1.]]
Synapse 1
[[-3.7004

In [49]:
import numpy as np

alphaValues = [0.001, 0.01, 0.1, 5, 10]

hiddenSize =32


# Defining a sigmoid function
def sigmoid(x):
    output = 1 / (1 + np.exp(-x))
    return output


# derivative of sigmoid function
def sigmoidDerivativeFunction(output):
    output = output * (1 - output)
    return output


# Some values to construct the nural net work
# Later we will be using the actual data from the iris data set

X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

for alpha in alphaValues:
    print("\the current alpha value = ", alpha)
    np.random.seed(1)

    # initializing Random weights

    weight_1 = 2 * np.random.random((3, hiddenSize)) - 1
    weight_2 = 2 * np.random.random((hiddenSize, 1)) - 1

    # checking the weights to see how the gradiants are changing

    weight_1_dirCount = np.zeros_like(weight_1)
    weight_2_dirCount = np.zeros_like(weight_2)

    prev_weight_1_update = np.zeros_like(weight_1)
    prev_weight_2_update = np.zeros_like(weight_2  )

    for j in range(60000):
        # Forward propogation from one layer to another i.e between layers 0 , 1, 2
        # layer_0 = X
        # layer_1 = sigmoid(np.dot(layer_0,weight_1))   #Here we are multiplying   ThetaTranspose* X
        # print(type(layer_1))
        # layer_2 = sigmoid(np.dot(layer_1,weight_2)) # the same thing with respoect to the second layer .. ie thetaTranspose*X

        layer_0 = X
        layer_1 = sigmoid(np.dot(layer_0, weight_1))
        layer_2 = sigmoid(np.dot(layer_1, weight_2))
        # Caliculating the error value

        ForwardPropError = y - layer_2

        if (j % 10000) == 0:
            print("Error = ", np.mean(np.abs(ForwardPropError)))

        ##Back propogation
        layer2_Sigma = ForwardPropError * sigmoidDerivativeFunction(layer_2)

        layer1_Error = layer2_Sigma.dot(weight_2.T)

        layer_1Sigma = layer1_Error * sigmoidDerivativeFunction(layer_1)

        # We are suggesting values .. i.e how much of it is wrong in each layer
        # baically updating the weights withs respective to values and the errors observed
        weight_2_Update = (layer_1.T.dot(layer2_Sigma))
        weight_1_Update = (layer_0.T.dot(layer_1Sigma))

        # We are checking what direction the gradient is moving
        if (j > 0):
            weight_1_dirCount += np.abs(((weight_1_Update > 0) + 0) -

                                        ((prev_weight_1_update > 0) + 0))
            weight_2_dirCount += np.abs(((weight_2_Update > 0) + 0) -

                                        ((prev_weight_2_update > 0) + 0))
        weight_1 += alpha * weight_1_Update
        weight_2 += alpha * weight_2_Update

        prev_weight_1_update = weight_1_Update
        prev_weight_2_update = weight_2_Update

    print("weight_1", weight_1)
    print("weight_2", weight_2)
    

	he current alpha value =  0.001
Error =  0.49643992250078794
Error =  0.49104946812904954
Error =  0.4849763070274596
Error =  0.4778306787926556
Error =  0.4690384653902826
Error =  0.458029258565275
weight_1 [[-0.66945036  0.44057532 -0.91759208 -0.36525547 -0.76011568 -0.82926418
  -0.61094522 -0.22947974 -0.67917735  0.15292538 -0.35220283  0.3339454
  -0.59142231  0.67756675 -1.11442476  0.54733702 -0.31555027  0.11348483
  -1.42577089 -0.75857317  0.67526556  0.75670996 -0.38885609  0.94740732
   0.79895388  1.35107823 -0.82206512 -0.99660592 -0.40374837  0.75100038
  -0.85239719 -0.11992929]
 [ 0.9583388   0.07763217  0.83646247 -0.34174625  0.57380012  0.64850887
  -0.90837847  0.49541604  0.96767225  0.50496084 -0.51623496  0.55803271
  -0.78484996 -0.25896594  1.37458204 -0.45776431 -0.51938006 -0.78121801
  -1.54926221  0.42897347 -0.82710662 -0.14644147  0.00949155 -1.04761586
  -0.17898997 -0.88967639 -0.25319071  0.77334008 -0.59686327 -0.16546404
   0.40869142 -0.146501

In [50]:
import numpy as np
alphaValues = [0.001, 0.01, 0.1, 5, 10]
hiddenSize =32
# Defining a sigmoid function
def sigmoid(x):
    output = 1 / (1 + np.exp(-x))
    return output


# derivative of sigmoid function
def sigmoidDerivativeFunction(output):
    output = output * (1 - output)
    return output

def forwardProp(X,weight_1,weight_2):
    ##Forward Propogation
    layer_0 = X
    layer_1 = sigmoid(np.dot(layer_0, weight_1))
    layer_2 = sigmoid(np.dot(layer_1, weight_2))
    return layer_0,layer_1,layer_2

def backwardProp(weight_1,weight_2,layer_1,layer_2,alpha,ForwardPropError):
    #Caliculating the error value
    layer_2_Sigma = ForwardPropError * sigmoidDerivativeFunction(layer_2)
    layer_1_Error = layer_2_Sigma.dot(weight_2.T)
    layer_1_Sigma = layer_1_Error * sigmoidDerivativeFunction(layer_1)
    # We are suggesting values .. i.e how much of it is wrong in each layer
    # baically updating the weights withs respective to values and the errors observed
    weight_1_Update = (layer_0.T.dot(layer_1_Sigma))
    weight_2_Update = (layer_1.T.dot(layer_2_Sigma))
    # We are checking what direction the gradient is moving
    weight_1 += alpha * weight_1_Update
    weight_2 += alpha * weight_2_Update
    return weight_1,weight_2
# Some values to construct the nural net work
# Later we will be using the actual data from the iris data set

X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

for alpha in alphaValues:
    print("\the current alpha value = ", alpha)
    np.random.seed(1)

    # initializing Random weights

    weight_1 = 2 * np.random.random((3, hiddenSize)) - 1
    weight_2 = 2 * np.random.random((hiddenSize, 1)) - 1

    # checking the weights to see how the gradiants are changing
    for j in range(60000):
        # Forward propogation from one layer to another i.e between layers 0 , 1, 2
        # Caliculating the error value
        layer_0,layer_1,layer_2 = forwardProp(X,weight_1,weight_2)
        ForwardPropError = y - layer_2
        if (j % 10000) == 0:
            print("Error = ", np.mean(np.abs(ForwardPropError)))
        weight_1,weight_2 = backwardProp(weight_1,weight_2,layer_1,layer_2,alpha,ForwardPropError)
    print("weight_1", weight_1)
    print("weight_2", weight_2)


	he current alpha value =  0.001
Error =  0.49643992250078794
Error =  0.49104946812904954
Error =  0.4849763070274596
Error =  0.4778306787926556
Error =  0.4690384653902826
Error =  0.458029258565275
weight_1 [[-0.66945036  0.44057532 -0.91759208 -0.36525547 -0.76011568 -0.82926418
  -0.61094522 -0.22947974 -0.67917735  0.15292538 -0.35220283  0.3339454
  -0.59142231  0.67756675 -1.11442476  0.54733702 -0.31555027  0.11348483
  -1.42577089 -0.75857317  0.67526556  0.75670996 -0.38885609  0.94740732
   0.79895388  1.35107823 -0.82206512 -0.99660592 -0.40374837  0.75100038
  -0.85239719 -0.11992929]
 [ 0.9583388   0.07763217  0.83646247 -0.34174625  0.57380012  0.64850887
  -0.90837847  0.49541604  0.96767225  0.50496084 -0.51623496  0.55803271
  -0.78484996 -0.25896594  1.37458204 -0.45776431 -0.51938006 -0.78121801
  -1.54926221  0.42897347 -0.82710662 -0.14644147  0.00949155 -1.04761586
  -0.17898997 -0.88967639 -0.25319071  0.77334008 -0.59686327 -0.16546404
   0.40869142 -0.146501